name: Build and Push GPU AI Image

on:
  push:
    branches:
      - main
      - kaggel

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Docker Buildx einrichten
        uses: docker/setup-buildx-action@v3

      - name: Bei GitHub Container Registry (GHCR) anmelden
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHT }}

      - name: Set up Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Der kaggel wird gebaut
        if: github.ref_name == 'kaggel'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: kaggel.Dockerfile
          push: true
          tags: ghcr.io/haider-yahiya/kaggel-ai-core:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Der main wird gebaut
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: main.Dockerfile
          push: true
          tags: ghcr.io/haider-yahiya/main-ai-core:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
